### ISSUE TITLE
Override artifact (XML/HTML) paths

### ISSUE THREAD

**Issue by gmayu** [elabit/robotmk#96]
Propose a new robotmk mode: In some cases RF tests are not launched using robotmk. For example, some RF tests are launched by Jenkins. But, by telling robotmk where the RF artifacts (e.g output.xml) are on the file system, robotmk in this mode would provide the similar functions as if the tests were launched by robotmk

**Comment by simonmeggle** [comment]
I like this idea, thanks for the proposal.
For this, the WATO bakery rule page should be extended in a way that the paths for XML and HTML can be overwritten with a path and a regex pattern to match the artifacts. 
XML and HTML files which carry timestamps in their names can be catched this way; Robotmk will try to always read the newest file. 

**Possible caveat:** it could happen that the newest XML gets read but the newest HTML is not present yet (because it contains screenhots and takes a little bit more time to get written). 
Robotmk will then read artifacts from different test cases.  .... How could we guarantee that always the corresponding files are read?

**Comment by simonmeggle** [comment]
Digging this out. 
This could be solved by an improvement of the "external" mode. In any way, the suites the robotmk-controller should collect results for, are set in `robotmk.yml`. Overriding the path and pattern to search for results could be solved as above. 

Further idea to integrate tests of e.g. Jenkins Jobs which only run _occasionally_: currently such tests cannot be integrated in Checkmk because Robotmk expects the results to be written _periodically_. => A `cache_time` of `-1` could indicate that the results of such sporadic tests are taken as valid _forever_. 

This would be a great feature to display the last/current results of e2e tests within a CI/CD pipeline.
